apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gff8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-gff8@sha256:4d4bbfdbb616901dc6b81b2a1f7efc072176a9d48d6bc9d1c34a1a217e9fcdc2
        name: my-nodejs
        resources: {}
status: {}
